apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-staging
  namespace: {{ .Values.project.code }}
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: sungwook.csw@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod
  namespace: {{ .Values.project.code }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: sungwook.csw@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx
