apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.project.code }}-clusterip
  namespace: {{ .Values.project.code }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.project.code }}-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
