apiVersion: apps/v1
kind: Deployment
metadata:
  name: cu-deployment
  namespace: cu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cu-app
  template:
    metadata:
      labels:
        app: cu-app
    spec:
      containers:
        - name: cu-container
          image: ghcr.io/noname2048/cu:latest
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: cu-configmap
      imagePullSecrets:
        - name: ghcr-secret
